# ===========
# PRODUCTION
# ===========
services:
  api_server:
    image: "${DOCKER_REGISTRY_URL}/catchup-backend:${IMAGE_TAG}"
    depends_on:
      - redis
    restart: always
    environment:
    # RDS Connection Info
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE:-catchup}
      - LOG_LEVEL=INFO
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "5"
  
  web_client:
    image: "${DOCKER_REGISTRY_URL}/catchup-web:${IMAGE_TAG}"
    restart: always
    environment:
      - NEXT_PUBLIC_API_URL=http://${NEXT_PUBLIC_API_URL}
  
