# ======
# Common
# ======
services:
  api_server:
    container_name: catchup_server
    profiles: ["backend", "full"]
    expose:
      - "8000"
    depends_on:
      redis:
        condition: service_started
    networks:
      - catchup_net
    environment:
      - ENABLE_NEO4J=${ENABLE_NEO4J:-False}
      - DB_HOST
      - DB_USER
      - DB_PASSWORD
      - REDIS_URL

  redis:
    container_name: catchup_redis
    image: redis/redis-stack-server:7.2.0-v13
    profiles: ["backend", "full"]
    volumes:
      - redis_data:/data
    networks:
      - catchup_net
    restart: always
    
  web_client:
    container_name: catchup_web
    profiles: ["frontend", "full"]
    expose:
      - "3000"
    networks:
      - catchup_net
      
  nginx:
    container_name: catchup_gateway
    image: nginx:1.28
    profiles: ["full"]
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api_server
      - web_client
    networks:
      - catchup_net
    
networks:
  catchup_net:
    driver: bridge

volumes:
  pg_data:
  redis_data: