# ===========
# PRODUCTION
# ===========
services:
  api_server:
    image: "${DOCKER_REGISTRY_URL}/catchup-backend:${IMAGE_TAG:-latest}"
    depends_on:
      - redis
    restart: always
    env_file:
      - .env
    environment:
    # RDS Connection Info
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE:-catchup}
      - LOG_LEVEL=INFO
    volumes:
      - ${LOG_EBS_PATH:-/mnt/ebs/catchup/logs}:/var/log/catchup
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "5"
  
  web_client:
    image: "${DOCKER_REGISTRY_URL}/catchup-web:${IMAGE_TAG:-latest}"
    env_file:
      - .env
    restart: always

  redis:
    ports:
      - "127.0.0.1:6379:6379"