from __future__ import annotations

VECTOR_STORE_TABLE_NAME = "vector_store"
VECTOR_STORE_ID_COLUMN = "id"
VECTOR_STORE_CONTENT_COLUMN = "content"
VECTOR_STORE_EMBEDDING_COLUMN = "embedding"

VECTOR_STORE_METADATA_COLUMN_NAMES = [
    "source",
    "entity_type",
    "scope_id",
    "target_id",
    "external_document_id",
    "chunk_identifier",
    "created_at",
    "updated_at",
]

# TODO : KNOWLEDGE STORE 관련 코드 삭제 후 제거
KNOWLEDGE_STORE_TABLE_NAME = VECTOR_STORE_TABLE_NAME
KNOWLEDGE_STORE_ID_COLUMN = VECTOR_STORE_ID_COLUMN
KNOWLEDGE_STORE_CONTENT_COLUMN = VECTOR_STORE_CONTENT_COLUMN
KNOWLEDGE_STORE_EMBEDDING_COLUMN = VECTOR_STORE_EMBEDDING_COLUMN
KNOWLEDGE_STORE_METADATA_JSON_COLUMN = "metadata"
KNOWLEDGE_STORE_METADATA_COLUMN_NAMES = VECTOR_STORE_METADATA_COLUMN_NAMES
