FULL_SYNC_EVENT_SCHEMA_VERSION = 2
LEGACY_FULL_SYNC_EVENT_SCHEMA_VERSION = 1

LEGACY_FULL_SYNC_IGNORED_REASON = "legacy_full_sync_format"
LEGACY_FULL_SYNC_LAST_ERROR = "ignored_legacy_full_sync_event"
