import type { Metadata } from 'next';
import '@/styles/globals.css';
import TopNavbar from '@/components/common/topNavbar/TopNavbar';
import SideNavbar from '@/components/common/sideNavbar/SideNavbar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="h-screen">
        <div className="flex h-full">
          <aside>
            <SideNavbar />
          </aside>
          <div className="flex flex-1 flex-col">
            <header className="h-[53px] flex-shrink-0">
              <TopNavbar />
            </header>
            <main className="flex-1 overflow-y-auto">{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
