"""check whether table exists before creating indices

Revision ID: 0f073e50fd8c
Revises: 9c522fb79518
Create Date: 2026-03-02 17:53:10.528528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f073e50fd8c'
down_revision: Union[str, Sequence[str], None] = '9c522fb79518'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 확장 설치
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_bigm")
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    
    # 테이블 존재 여부 확인
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()

    # 테이블이 있을 때만 인덱스 생성 시도
    if "langchain_pg_embedding" in tables:
        op.execute("""
            CREATE INDEX IF NOT EXISTS idx_cmetadata_source
            ON langchain_pg_embedding ((cmetadata ->> 'source'))
        """)
        
        op.execute("""
            CREATE INDEX IF NOT EXISTS idx_cmetadata_updated_at
            ON langchain_pg_embedding ((cmetadata ->> 'updated_at'))
        """)
        
        op.execute("""
            CREATE INDEX IF NOT EXISTS idx_cmetadata_created_at
            ON langchain_pg_embedding ((cmetadata ->> 'created_at'))
        """)
        
        op.execute("""
            CREATE INDEX IF NOT EXISTS idx_fts_korean_bigm 
            ON langchain_pg_embedding USING GIN (document gin_bigm_ops)
        """)
    else:
        # 테이블이 없으면 서버 실행 시 생성될 것이므로, 로그만 남김
        print("\n[SKIP] 'langchain_pg_embedding' 테이블이 없어 인덱스 생성을 스킵합니다.")
        print("[INFO] 서버 실행 후 LangChain에 의해 테이블이 생성되면 다시 실행하세요.\n")
    
    
    op.alter_column('pre_mapping_buffers', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='OAuth 사용자 이메일 (예: Keycloak 이메일)',
               existing_comment='Catch Up 사용자 이메일 (예: Keycloak 이메일)',
               existing_nullable=False)
    
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pre_mapping_buffers', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='Catch Up 사용자 이메일 (예: Keycloak 이메일)',
               existing_comment='OAuth 사용자 이메일 (예: Keycloak 이메일)',
               existing_nullable=False)
    # ### end Alembic commands ###
