"""Add trace_id to chat_histories

Revision ID: 740d7e16753a
Revises: aabc26fe93df
Create Date: 2026-03-17 08:57:58.000410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '740d7e16753a'
down_revision: Union[str, Sequence[str], None] = 'aabc26fe93df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_histories', sa.Column('trace_id', sa.String(length=64), nullable=True, comment='Langfuse trace에 사용자 피드백을 사후 반영하기 위한 식별자'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_histories', 'trace_id')
    # ### end Alembic commands ###
