"""Add rerank_count column to ChatTokenUsage

Revision ID: 95e7a47233a9
Revises: 8f3a2c1d4b5e
Create Date: 2026-03-24 02:42:42.696703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95e7a47233a9'
down_revision: Union[str, Sequence[str], None] = '8f3a2c1d4b5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_token_usages', sa.Column('rerank_count', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_token_usages', 'rerank_count')
    # ### end Alembic commands ###
