"""add user_prompt_settings

Revision ID: 358d249f6a1f
Revises: 4f91c2ab7d1e
Create Date: 2026-04-10 03:48:16.006278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '358d249f6a1f'
down_revision: Union[str, Sequence[str], None] = '4f91c2ab7d1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    
    # user_prompt_settings 테이블 추가
    op.create_table('user_prompt_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_role', sa.String(length=50), nullable=True),
    sa.Column('custom_job_text', sa.String(length=50), nullable=True),
    sa.Column('job_description', sa.String(length=200), nullable=True),
    sa.Column('selected_options', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('custom_prompt', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    
    # 기존 User.custom_prompt를 복사
    op.execute("""
        INSERT INTO user_prompt_settings (user_id, custom_prompt)
        SELECT id, custom_prompt
        FROM users
        WHERE custom_prompt IS NOT NULL
    """)
    
    # inactive_users 테이블 & 인덱스 제거
    if inspector.has_table("inactive_users"):
        indexes = {idx["name"] for idx in inspector.get_indexes("inactive_users")}
        if "idx_inactive_users_user_id" in indexes:
            op.drop_index("idx_inactive_users_user_id", table_name="inactive_users")
        op.drop_table("inactive_users")
    
    # slack_chat_threads 제약 조건 반영
    op.alter_column('slack_chat_threads', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('slack_chat_threads', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    constraints = {c["name"] for c in inspector.get_unique_constraints("slack_chat_threads")}
    if "slack_chat_threads_session_id_key" in constraints:
        op.drop_constraint("slack_chat_threads_session_id_key", "slack_chat_threads", type_="unique")



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('slack_chat_threads_session_id_key'), 'slack_chat_threads', ['session_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('slack_chat_threads', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('slack_chat_threads', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_table('user_prompt_settings')
    # ### end Alembic commands ###
