"""add user_id column to chat_histories

Revision ID: 09a0daaececa
Revises: 8ca6c1995d03
Create Date: 2026-04-12 06:47:38.780295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09a0daaececa'
down_revision: Union[str, Sequence[str], None] = '8ca6c1995d03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_histories', sa.Column('user_id', sa.Integer(), nullable=True, comment='메시지 발신 유저 (Slack 멀티유저 귀속용, 레거시 레코드는 NULL)'))
    op.create_index(op.f('ix_chat_histories_user_id'), 'chat_histories', ['user_id'], unique=False)
    op.create_foreign_key(None, 'chat_histories', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_histories', type_='foreignkey')
    op.drop_index(op.f('ix_chat_histories_user_id'), table_name='chat_histories')
    op.drop_column('chat_histories', 'user_id')
    # ### end Alembic commands ###
