"""drop custom_prompt from users table

Revision ID: a5e040dfd8b7
Revises: 358d249f6a1f
Create Date: 2026-04-10 05:22:48.008483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5e040dfd8b7'
down_revision: Union[str, Sequence[str], None] = '358d249f6a1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'custom_prompt')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('custom_prompt', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
