"""channel_talk_managers_comment_modification

Revision ID: 61e30cd579bf
Revises: 7a1c5f0e2d4b
Create Date: 2026-04-21 04:36:23.927597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61e30cd579bf'
down_revision: Union[str, Sequence[str], None] = '7a1c5f0e2d4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('channel_talk_managers', 'role_id',
               existing_type=sa.VARCHAR(length=50),
               comment='Manager role ID',
               existing_comment='Manager role ID returned by Channel Talk',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('channel_talk_managers', 'role_id',
               existing_type=sa.VARCHAR(length=50),
               comment='Manager role ID returned by Channel Talk',
               existing_comment='Manager role ID',
               existing_nullable=True)
    # ### end Alembic commands ###
