"""add unique constraint to channel talk credentials channel id

Revision ID: 03e3080a656c
Revises: b4c7d9e1a2f3
Create Date: 2026-04-30 21:29:35.394390

"""
from typing import Sequence
from typing import Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "03e3080a656c"
down_revision: Union[str, Sequence[str], None] = "b4c7d9e1a2f3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_channel_talk_credentials_channel_id",
        "channel_talk_credentials",
        ["channel_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_channel_talk_credentials_channel_id",
        "channel_talk_credentials",
        type_="unique",
    )
    # ### end Alembic commands ###
