"""Add manual_search_histories

Revision ID: 649538fd2274
Revises: 7d3c2a1b9e4f
Create Date: 2026-05-13 05:08:32.728008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '649538fd2274'
down_revision: Union[str, Sequence[str], None] = '7d3c2a1b9e4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manual_search_histories',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_manual_search_histories_user_created_at', 'manual_search_histories', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_manual_search_histories_user_id'), 'manual_search_histories', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_manual_search_histories_user_id'), table_name='manual_search_histories')
    op.drop_index('idx_manual_search_histories_user_created_at', table_name='manual_search_histories')
    op.drop_table('manual_search_histories')
    # ### end Alembic commands ###
