"""update agent trigger schema for normalized events

Revision ID: 79d57733f8c0
Revises: d598d574a0ab
Create Date: 2026-05-28 15:00:56.188547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '79d57733f8c0'
down_revision: Union[str, Sequence[str], None] = 'd598d574a0ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - adjusted for existing rows ###
    op.add_column('agent_triggers', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.add_column('agent_triggers', sa.Column('name', sa.String(length=100), nullable=True))
    op.add_column('agent_triggers', sa.Column('event_type', sa.String(length=100), nullable=True))
    op.add_column('agent_triggers', sa.Column('condition', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    op.add_column('agent_triggers', sa.Column('concurrency_key', sa.String(length=255), nullable=True))
    op.add_column('agent_triggers', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.execute("""
        UPDATE agent_triggers AS t
        SET
            workspace_id = spec.workspace_id,
            name = 'Agent Trigger ' || t.id::text,
            event_type = COALESCE(
                spec.spec #>> '{trigger,config,event_type}',
                'legacy.unspecified'
            ),
            condition = COALESCE(t.filter_condition, '{}'::jsonb)
        FROM agent_specs AS spec
        WHERE t.agent_spec_id = spec.id
    """)
    op.alter_column('agent_triggers', 'workspace_id',
               existing_type=sa.Integer(),
               nullable=False)
    op.alter_column('agent_triggers', 'name',
               existing_type=sa.String(length=100),
               nullable=False)
    op.alter_column('agent_triggers', 'event_type',
               existing_type=sa.String(length=100),
               nullable=False)
    op.alter_column('agent_triggers', 'source',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_index(op.f('idx_agent_triggers_source'), table_name='agent_triggers')
    op.create_index('idx_agent_triggers_lookup', 'agent_triggers', ['workspace_id', 'source', 'event_type'], unique=False)
    op.create_index('idx_agent_triggers_agent_spec_id', 'agent_triggers', ['agent_spec_id'], unique=False)
    op.create_index('idx_agent_triggers_concurrency_key', 'agent_triggers', ['workspace_id', 'concurrency_key'], unique=False)
    op.create_foreign_key('fk_agent_triggers_workspace_id_workspaces', 'agent_triggers', 'workspaces', ['workspace_id'], ['id'])
    op.drop_column('agent_triggers', 'filter_condition')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - adjusted for named foreign key ###
    op.add_column('agent_triggers', sa.Column('filter_condition', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.execute("""
        UPDATE agent_triggers
        SET filter_condition = condition
    """)
    op.drop_constraint('fk_agent_triggers_workspace_id_workspaces', 'agent_triggers', type_='foreignkey')
    op.drop_index('idx_agent_triggers_concurrency_key', table_name='agent_triggers')
    op.drop_index('idx_agent_triggers_agent_spec_id', table_name='agent_triggers')
    op.drop_index('idx_agent_triggers_lookup', table_name='agent_triggers')
    op.create_index(op.f('idx_agent_triggers_source'), 'agent_triggers', ['type', 'source'], unique=False)
    op.alter_column('agent_triggers', 'source',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('agent_triggers', 'updated_at')
    op.drop_column('agent_triggers', 'concurrency_key')
    op.drop_column('agent_triggers', 'condition')
    op.drop_column('agent_triggers', 'event_type')
    op.drop_column('agent_triggers', 'name')
    op.drop_column('agent_triggers', 'workspace_id')
    # ### end Alembic commands ###
