"""add knowledge resolution tables

Revision ID: c5308d1a3f09
Revises: 27c8259a2c1c
Create Date: 2026-07-29 16:41:38.082873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c5308d1a3f09'
down_revision: Union[str, Sequence[str], None] = '27c8259a2c1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_node_aliases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('alias', sa.Text(), nullable=False),
    sa.Column('normalized_alias', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('source', 'extractor', 'human', 'system')", name='ck_knowledge_node_aliases_source'),
    sa.ForeignKeyConstraint(['workspace_id', 'node_id'], ['knowledge_nodes.workspace_id', 'knowledge_nodes.id'], name='fk_knowledge_node_aliases_node', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'node_id', 'normalized_alias', name='uq_knowledge_node_aliases_normalized')
    )
    op.create_index('ix_knowledge_node_aliases_lookup', 'knowledge_node_aliases', ['workspace_id', 'normalized_alias'], unique=False)
    op.create_table('knowledge_mutation_proposals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('trigger_entity_candidate_id', sa.UUID(), nullable=True),
    sa.Column('trigger_claim_candidate_id', sa.UUID(), nullable=True),
    sa.Column('trigger_relation_assertion_candidate_id', sa.UUID(), nullable=True),
    sa.Column('proposal_kind', sa.String(length=16), nullable=False),
    sa.Column('detector', sa.String(length=64), nullable=False),
    sa.Column('detector_version', sa.String(length=64), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('resolver_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("proposal_kind IN ('create', 'duplicate', 'contradiction', 'mixed')", name='ck_knowledge_mutation_proposals_kind'),
    sa.CheckConstraint("status IN ('pending', 'applied', 'stale', 'abandoned')", name='ck_knowledge_mutation_proposals_status'),
    sa.CheckConstraint('num_nonnulls(trigger_entity_candidate_id, trigger_claim_candidate_id, trigger_relation_assertion_candidate_id) = 1', name='ck_knowledge_mutation_proposals_exactly_one_trigger'),
    sa.ForeignKeyConstraint(['workspace_id', 'trigger_claim_candidate_id'], ['knowledge_claim_candidates.workspace_id', 'knowledge_claim_candidates.id'], name='fk_knowledge_mutation_proposals_claim_candidate'),
    sa.ForeignKeyConstraint(['workspace_id', 'trigger_entity_candidate_id'], ['knowledge_entity_candidates.workspace_id', 'knowledge_entity_candidates.id'], name='fk_knowledge_mutation_proposals_entity_candidate'),
    sa.ForeignKeyConstraint(['workspace_id', 'trigger_relation_assertion_candidate_id'], ['knowledge_relation_assertion_candidates.workspace_id', 'knowledge_relation_assertion_candidates.id'], name='fk_knowledge_mutation_proposals_relation_candidate'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'id', name='uq_knowledge_mutation_proposals_workspace_id_id'),
    sa.UniqueConstraint('workspace_id', 'idempotency_key', name='uq_knowledge_mutation_proposals_idempotency_key')
    )
    op.create_index('ix_knowledge_mutation_proposals_review_queue', 'knowledge_mutation_proposals', ['workspace_id', 'status', 'created_at'], unique=False)
    op.create_table('knowledge_mutation_operations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('operation_type', sa.String(length=32), nullable=False),
    sa.Column('entity_candidate_id', sa.UUID(), nullable=True),
    sa.Column('claim_candidate_id', sa.UUID(), nullable=True),
    sa.Column('relation_assertion_candidate_id', sa.UUID(), nullable=True),
    sa.Column('target_node_id', sa.UUID(), nullable=True),
    sa.Column('evidence_node_id', sa.UUID(), nullable=True),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('operation_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("operation_type IN ('create_entity', 'merge_entity', 'create_claim', 'invalidate_claim', 'supersede_claim', 'create_relation_assertion', 'invalidate_relation_assertion', 'supersede_relation_assertion', 'attach_evidence')", name='ck_knowledge_mutation_operations_type'),
    sa.CheckConstraint('sequence >= 1', name='ck_knowledge_mutation_operations_sequence'),
    sa.ForeignKeyConstraint(['workspace_id', 'claim_candidate_id'], ['knowledge_claim_candidates.workspace_id', 'knowledge_claim_candidates.id'], name='fk_knowledge_mutation_operations_claim_candidate'),
    sa.ForeignKeyConstraint(['workspace_id', 'entity_candidate_id'], ['knowledge_entity_candidates.workspace_id', 'knowledge_entity_candidates.id'], name='fk_knowledge_mutation_operations_entity_candidate'),
    sa.ForeignKeyConstraint(['workspace_id', 'evidence_node_id'], ['knowledge_nodes.workspace_id', 'knowledge_nodes.id'], name='fk_knowledge_mutation_operations_evidence_node'),
    sa.ForeignKeyConstraint(['workspace_id', 'proposal_id'], ['knowledge_mutation_proposals.workspace_id', 'knowledge_mutation_proposals.id'], name='fk_knowledge_mutation_operations_proposal', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id', 'relation_assertion_candidate_id'], ['knowledge_relation_assertion_candidates.workspace_id', 'knowledge_relation_assertion_candidates.id'], name='fk_knowledge_mutation_operations_relation_candidate'),
    sa.ForeignKeyConstraint(['workspace_id', 'target_node_id'], ['knowledge_nodes.workspace_id', 'knowledge_nodes.id'], name='fk_knowledge_mutation_operations_target_node'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proposal_id', 'sequence', name='uq_knowledge_mutation_operations_sequence')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('knowledge_mutation_operations')
    op.drop_index('ix_knowledge_mutation_proposals_review_queue', table_name='knowledge_mutation_proposals')
    op.drop_table('knowledge_mutation_proposals')
    op.drop_index('ix_knowledge_node_aliases_lookup', table_name='knowledge_node_aliases')
    op.drop_table('knowledge_node_aliases')
    # ### end Alembic commands ###
