"""add knowledge ontology snapshots

Revision ID: e50f139b0bf8
Revises: 7601a0e7b7fb
Create Date: 2026-07-28 21:22:04.172652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e50f139b0bf8'
down_revision: Union[str, Sequence[str], None] = '7601a0e7b7fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_ontology_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('ontology_id', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('predicates', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('relation_types', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'ontology_id', 'version', name='uq_knowledge_ontology_snapshots_version')
    )
    op.create_foreign_key('fk_knowledge_extraction_runs_ontology', 'knowledge_extraction_runs', 'knowledge_ontology_snapshots', ['workspace_id', 'ontology_id', 'ontology_version'], ['workspace_id', 'ontology_id', 'version'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_knowledge_extraction_runs_ontology', 'knowledge_extraction_runs', type_='foreignkey')
    op.drop_table('knowledge_ontology_snapshots')
    # ### end Alembic commands ###
