"""add knowledge_nodes table

Revision ID: c675925fbee0
Revises: 3475ff48126a
Create Date: 2026-07-28 19:52:21.071401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c675925fbee0'
down_revision: Union[str, Sequence[str], None] = '3475ff48126a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('node_kind', sa.String(length=32), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=True),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('entity_type', sa.String(length=128), nullable=True),
    sa.Column('canonical_key', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('lifecycle_state', sa.String(length=16), server_default=sa.text("'active'"), nullable=False),
    sa.Column('merged_into_node_id', sa.UUID(), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(lifecycle_state = 'merged' AND merged_into_node_id IS NOT NULL) OR (lifecycle_state <> 'merged' AND merged_into_node_id IS NULL)", name='ck_knowledge_nodes_merged_target'),
    sa.CheckConstraint("lifecycle_state IN ('active', 'merged', 'retired')", name='ck_knowledge_nodes_lifecycle_state'),
    sa.CheckConstraint("node_kind IN ('source_version', 'observation', 'entity', 'claim', 'relation_assertion', 'artifact', 'artifact_revision', 'review_decision', 'editorial_override')", name='ck_knowledge_nodes_node_kind'),
    sa.ForeignKeyConstraint(['workspace_id', 'merged_into_node_id'], ['knowledge_nodes.workspace_id', 'knowledge_nodes.id'], name='fk_knowledge_nodes_merged_into'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'id', name='uq_knowledge_nodes_workspace_id_id')
    )
    op.create_index('ix_knowledge_nodes_workspace_kind', 'knowledge_nodes', ['workspace_id', 'node_kind', 'lifecycle_state'], unique=False)
    op.create_index('uq_knowledge_nodes_canonical_entity', 'knowledge_nodes', ['workspace_id', 'entity_type', 'canonical_key'], unique=True, postgresql_where=sa.text("node_kind = 'entity' AND canonical_key IS NOT NULL"))
    op.create_index('uq_knowledge_nodes_resource', 'knowledge_nodes', ['workspace_id', 'resource_type', 'resource_id'], unique=True, postgresql_where=sa.text('resource_type IS NOT NULL AND resource_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_knowledge_nodes_resource', table_name='knowledge_nodes', postgresql_where=sa.text('resource_type IS NOT NULL AND resource_id IS NOT NULL'))
    op.drop_index('uq_knowledge_nodes_canonical_entity', table_name='knowledge_nodes', postgresql_where=sa.text("node_kind = 'entity' AND canonical_key IS NOT NULL"))
    op.drop_index('ix_knowledge_nodes_workspace_kind', table_name='knowledge_nodes')
    op.drop_table('knowledge_nodes')
    # ### end Alembic commands ###
