"""add knowledge candidate staging tables

Revision ID: 7601a0e7b7fb
Revises: c675925fbee0
Create Date: 2026-07-28 20:37:38.888301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7601a0e7b7fb'
down_revision: Union[str, Sequence[str], None] = 'c675925fbee0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_extraction_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('input_node_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('extractor_version', sa.String(length=128), nullable=False),
    sa.Column('prompt_version', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('raw_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('running', 'succeeded', 'failed')", name='ck_knowledge_extraction_runs_status'),
    sa.ForeignKeyConstraint(['workspace_id', 'input_node_id'], ['knowledge_nodes.workspace_id', 'knowledge_nodes.id'], name='fk_knowledge_extraction_runs_input_node'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'id', name='uq_knowledge_extraction_runs_workspace_id_id')
    )
    op.create_index('ix_knowledge_extraction_runs_input_node', 'knowledge_extraction_runs', ['workspace_id', 'input_node_id', 'started_at'], unique=False)
    op.create_table('knowledge_entity_candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('extraction_run_id', sa.UUID(), nullable=False),
    sa.Column('local_key', sa.String(length=255), nullable=False),
    sa.Column('proposed_type', sa.String(length=128), nullable=False),
    sa.Column('proposed_name', sa.Text(), nullable=False),
    sa.Column('extraction_method', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Numeric(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('resolution_status', sa.String(length=16), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('resolved_node_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("extraction_method IN ('deterministic', 'llm')", name='ck_knowledge_entity_candidates_extraction_method'),
    sa.CheckConstraint("resolution_status IN ('pending', 'accepted', 'merged', 'rejected')", name='ck_knowledge_entity_candidates_resolution_status'),
    sa.ForeignKeyConstraint(['workspace_id', 'extraction_run_id'], ['knowledge_extraction_runs.workspace_id', 'knowledge_extraction_runs.id'], name='fk_knowledge_entity_candidates_run', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id', 'resolved_node_id'], ['knowledge_nodes.workspace_id', 'knowledge_nodes.id'], name='fk_knowledge_entity_candidates_resolved_node'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('extraction_run_id', 'local_key', name='uq_knowledge_entity_candidates_run_local_key'),
    sa.UniqueConstraint('workspace_id', 'id', name='uq_knowledge_entity_candidates_workspace_id_id')
    )
    op.create_table('knowledge_claim_candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('extraction_run_id', sa.UUID(), nullable=False),
    sa.Column('local_key', sa.String(length=255), nullable=False),
    sa.Column('subject_entity_candidate_id', sa.UUID(), nullable=True),
    sa.Column('subject_node_id', sa.UUID(), nullable=True),
    sa.Column('predicate', sa.String(length=128), nullable=False),
    sa.Column('value_type', sa.String(length=32), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('value_hash', sa.String(length=64), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ontology_id', sa.String(length=128), nullable=False),
    sa.Column('ontology_version', sa.String(length=64), nullable=False),
    sa.Column('extraction_method', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Numeric(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('resolution_status', sa.String(length=16), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('resolved_claim_node_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("extraction_method IN ('deterministic', 'llm')", name='ck_knowledge_claim_candidates_extraction_method'),
    sa.CheckConstraint("resolution_status IN ('pending', 'accepted', 'duplicate', 'rejected')", name='ck_knowledge_claim_candidates_resolution_status'),
    sa.CheckConstraint('(subject_entity_candidate_id IS NULL) <> (subject_node_id IS NULL)', name='ck_knowledge_claim_candidates_subject_exactly_one'),
    sa.CheckConstraint('valid_to IS NULL OR valid_from IS NULL OR valid_to > valid_from', name='ck_knowledge_claim_candidates_valid_range'),
    sa.ForeignKeyConstraint(['workspace_id', 'extraction_run_id'], ['knowledge_extraction_runs.workspace_id', 'knowledge_extraction_runs.id'], name='fk_knowledge_claim_candidates_run', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id', 'resolved_claim_node_id'], ['knowledge_nodes.workspace_id', 'knowledge_nodes.id'], name='fk_knowledge_claim_candidates_resolved_node'),
    sa.ForeignKeyConstraint(['workspace_id', 'subject_entity_candidate_id'], ['knowledge_entity_candidates.workspace_id', 'knowledge_entity_candidates.id'], name='fk_knowledge_claim_candidates_subject_candidate', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id', 'subject_node_id'], ['knowledge_nodes.workspace_id', 'knowledge_nodes.id'], name='fk_knowledge_claim_candidates_subject_node'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('extraction_run_id', 'local_key', name='uq_knowledge_claim_candidates_run_local_key'),
    sa.UniqueConstraint('workspace_id', 'id', name='uq_knowledge_claim_candidates_workspace_id_id')
    )
    op.create_index('ix_knowledge_claim_candidates_lookup', 'knowledge_claim_candidates', ['workspace_id', 'predicate', 'value_hash'], unique=False)
    op.create_table('knowledge_relation_assertion_candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('extraction_run_id', sa.UUID(), nullable=False),
    sa.Column('local_key', sa.String(length=255), nullable=False),
    sa.Column('source_entity_candidate_id', sa.UUID(), nullable=True),
    sa.Column('source_node_id', sa.UUID(), nullable=True),
    sa.Column('target_entity_candidate_id', sa.UUID(), nullable=True),
    sa.Column('target_node_id', sa.UUID(), nullable=True),
    sa.Column('relation_type', sa.String(length=128), nullable=False),
    sa.Column('assertion_text', sa.Text(), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extraction_method', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Numeric(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('resolution_status', sa.String(length=16), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('resolved_relation_node_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("extraction_method IN ('deterministic', 'llm')", name='ck_knowledge_relation_candidates_extraction_method'),
    sa.CheckConstraint("resolution_status IN ('pending', 'accepted', 'duplicate', 'rejected')", name='ck_knowledge_relation_candidates_resolution_status'),
    sa.CheckConstraint('(source_entity_candidate_id IS NULL) <> (source_node_id IS NULL)', name='ck_knowledge_relation_candidates_source_exactly_one'),
    sa.CheckConstraint('(target_entity_candidate_id IS NULL) <> (target_node_id IS NULL)', name='ck_knowledge_relation_candidates_target_exactly_one'),
    sa.CheckConstraint('valid_to IS NULL OR valid_from IS NULL OR valid_to > valid_from', name='ck_knowledge_relation_candidates_valid_range'),
    sa.ForeignKeyConstraint(['workspace_id', 'extraction_run_id'], ['knowledge_extraction_runs.workspace_id', 'knowledge_extraction_runs.id'], name='fk_knowledge_relation_candidates_run', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id', 'resolved_relation_node_id'], ['knowledge_nodes.workspace_id', 'knowledge_nodes.id'], name='fk_knowledge_relation_candidates_resolved_node'),
    sa.ForeignKeyConstraint(['workspace_id', 'source_entity_candidate_id'], ['knowledge_entity_candidates.workspace_id', 'knowledge_entity_candidates.id'], name='fk_knowledge_relation_candidates_source_candidate', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id', 'source_node_id'], ['knowledge_nodes.workspace_id', 'knowledge_nodes.id'], name='fk_knowledge_relation_candidates_source_node'),
    sa.ForeignKeyConstraint(['workspace_id', 'target_entity_candidate_id'], ['knowledge_entity_candidates.workspace_id', 'knowledge_entity_candidates.id'], name='fk_knowledge_relation_candidates_target_candidate', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id', 'target_node_id'], ['knowledge_nodes.workspace_id', 'knowledge_nodes.id'], name='fk_knowledge_relation_candidates_target_node'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('extraction_run_id', 'local_key', name='uq_knowledge_relation_candidates_run_local_key'),
    sa.UniqueConstraint('workspace_id', 'id', name='uq_knowledge_relation_candidates_workspace_id_id')
    )
    op.create_table('knowledge_candidate_evidence_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('extraction_run_id', sa.UUID(), nullable=False),
    sa.Column('entity_candidate_id', sa.UUID(), nullable=True),
    sa.Column('claim_candidate_id', sa.UUID(), nullable=True),
    sa.Column('relation_assertion_candidate_id', sa.UUID(), nullable=True),
    sa.Column('evidence_node_id', sa.UUID(), nullable=False),
    sa.Column('evidence_role', sa.String(length=32), server_default=sa.text("'supports'"), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('locator', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("evidence_role IN ('supports', 'contradicts')", name='ck_knowledge_candidate_evidence_links_role'),
    sa.CheckConstraint('num_nonnulls(entity_candidate_id, claim_candidate_id, relation_assertion_candidate_id) = 1', name='ck_knowledge_candidate_evidence_links_exactly_one_target'),
    sa.ForeignKeyConstraint(['workspace_id', 'claim_candidate_id'], ['knowledge_claim_candidates.workspace_id', 'knowledge_claim_candidates.id'], name='fk_knowledge_candidate_evidence_links_claim', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id', 'entity_candidate_id'], ['knowledge_entity_candidates.workspace_id', 'knowledge_entity_candidates.id'], name='fk_knowledge_candidate_evidence_links_entity', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id', 'evidence_node_id'], ['knowledge_nodes.workspace_id', 'knowledge_nodes.id'], name='fk_knowledge_candidate_evidence_links_evidence_node'),
    sa.ForeignKeyConstraint(['workspace_id', 'extraction_run_id'], ['knowledge_extraction_runs.workspace_id', 'knowledge_extraction_runs.id'], name='fk_knowledge_candidate_evidence_links_run', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id', 'relation_assertion_candidate_id'], ['knowledge_relation_assertion_candidates.workspace_id', 'knowledge_relation_assertion_candidates.id'], name='fk_knowledge_candidate_evidence_links_relation', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_knowledge_candidate_evidence_links_evidence_node', 'knowledge_candidate_evidence_links', ['workspace_id', 'evidence_node_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_knowledge_candidate_evidence_links_evidence_node', table_name='knowledge_candidate_evidence_links')
    op.drop_table('knowledge_candidate_evidence_links')
    op.drop_table('knowledge_relation_assertion_candidates')
    op.drop_index('ix_knowledge_claim_candidates_lookup', table_name='knowledge_claim_candidates')
    op.drop_table('knowledge_claim_candidates')
    op.drop_table('knowledge_entity_candidates')
    op.drop_index('ix_knowledge_extraction_runs_input_node', table_name='knowledge_extraction_runs')
    op.drop_table('knowledge_extraction_runs')
    # ### end Alembic commands ###
