"""add knowledge pipeline outbox

Revision ID: 27c8259a2c1c
Revises: e50f139b0bf8
Create Date: 2026-07-28 22:02:14.137884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '27c8259a2c1c'
down_revision: Union[str, Sequence[str], None] = 'e50f139b0bf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_pipeline_outbox',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('aggregate_type', sa.String(length=64), nullable=False),
    sa.Column('aggregate_id', sa.UUID(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("aggregate_type IN ('observation')", name='ck_knowledge_pipeline_outbox_aggregate_type'),
    sa.CheckConstraint("event_type IN ('observation.ready')", name='ck_knowledge_pipeline_outbox_event_type'),
    sa.CheckConstraint("status IN ('pending', 'processing', 'processed', 'failed')", name='ck_knowledge_pipeline_outbox_status'),
    sa.CheckConstraint('attempts >= 0', name='ck_knowledge_pipeline_outbox_attempts'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_type', 'aggregate_type', 'aggregate_id', name='uq_knowledge_pipeline_outbox_event')
    )
    op.create_index('ix_knowledge_pipeline_outbox_claim', 'knowledge_pipeline_outbox', ['status', 'available_at', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_knowledge_pipeline_outbox_claim', table_name='knowledge_pipeline_outbox')
    op.drop_table('knowledge_pipeline_outbox')
    # ### end Alembic commands ###
