"""add test knowledge maintaince settings

Revision ID: 174617949f26
Revises: 6c8b2659938b
Create Date: 2026-08-14 22:54:57.976608

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "174617949f26"
down_revision: str | Sequence[str] | None = "6c8b2659938b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "test_knowledge_maintaince_settings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("workspace_id", sa.Integer(), nullable=False),
        sa.Column("channel_talk_credential_id", sa.Integer(), nullable=False),
        sa.Column(
            "enabled",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "execution_anchor_at", sa.DateTime(timezone=True), nullable=False
        ),
        sa.Column("interval_minutes", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "interval_minutes > 0",
            name="ck_test_knowledge_maintaince_interval_positive",
        ),
        sa.ForeignKeyConstraint(
            ["channel_talk_credential_id"],
            ["channel_talk_credentials.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"], ["workspaces.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "workspace_id",
            "channel_talk_credential_id",
            name="uq_test_knowledge_maintaince_workspace_credential",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("test_knowledge_maintaince_settings")
    # ### end Alembic commands ###
