"""fix(User): output_tokens 오타 수정

Revision ID: 1aa6f915958b
Revises: da9acad91875
Create Date: 2026-02-14 14:38:03.448465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1aa6f915958b'
down_revision: Union[str, Sequence[str], None] = 'da9acad91875'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_histories', sa.Column('output_tokens', sa.Integer(), nullable=True))
    op.drop_column('chat_histories', 'outpu_tokens')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_histories', sa.Column('outpu_tokens', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('chat_histories', 'output_tokens')
    # ### end Alembic commands ###
