"""ChatHistory: feedback 관련 필드 추가

Revision ID: 3e0aa44fd8bd
Revises: 1aa6f915958b
Create Date: 2026-02-14 18:16:06.997571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3e0aa44fd8bd'
down_revision: Union[str, Sequence[str], None] = '1aa6f915958b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_histories', sa.Column('is_liked', sa.Boolean(), nullable=True, comment='True: 긍정, False: 부정, None: 평가 없음'))
    op.add_column('chat_histories', sa.Column('feedback_reasons', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True, comment='사용자가 선택한 부정 피드백 사유 목록 (Json Array)'))
    op.add_column('chat_histories', sa.Column('feedback_comment', sa.Text(), nullable=True, comment='사용자가 직접 작성한 상세 피드백 내용'))
    op.drop_column('chat_histories', 'feedback_string')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_histories', sa.Column('feedback_string', sa.VARCHAR(length=127), autoincrement=False, nullable=True))
    op.drop_column('chat_histories', 'feedback_comment')
    op.drop_column('chat_histories', 'feedback_reasons')
    op.drop_column('chat_histories', 'is_liked')
    # ### end Alembic commands ###
