"""Nullable message_id in chat_token_usages

Revision ID: 60c21457ca11
Revises: 3c6d4f8a9b21
Create Date: 2026-03-31 04:53:20.501896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60c21457ca11'
down_revision: Union[str, Sequence[str], None] = '3c6d4f8a9b21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_token_usages', 'message_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='purpose가 title_generation인 경우 NULL 허용')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_token_usages', 'message_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='purpose가 title_generation인 경우 NULL 허용')
    # ### end Alembic commands ###
