"""Initial migration

Revision ID: aabc26fe93df
Revises: 
Create Date: 2026-03-31 08:41:34.367918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aabc26fe93df'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atlassian_oauth_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('atlassian_account_id', sa.String(length=128), nullable=False),
    sa.Column('cloud_id', sa.String(length=128), nullable=False),
    sa.Column('site_name', sa.String(length=255), nullable=True),
    sa.Column('site_url', sa.String(length=500), nullable=True),
    sa.Column('access_token', sa.String(length=4096), nullable=False),
    sa.Column('refresh_token', sa.String(length=4096), nullable=False),
    sa.Column('token_type', sa.String(length=50), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='Access Token 만료 시간'),
    sa.Column('scopes', sa.String(length=1000), nullable=True, comment='Jira + Confluence + Atlassian 공통 Scope 포함'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_atlassian_oauth_tokens_cloud_id'), 'atlassian_oauth_tokens', ['cloud_id'], unique=True)
    op.create_table('companies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('size', sa.String(length=20), server_default=sa.text("'small'"), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('confluence_spaces',
    sa.Column('cloud_id', sa.String(length=128), nullable=False),
    sa.Column('space_id', sa.String(length=32), nullable=False),
    sa.Column('space_key', sa.String(length=128), nullable=False),
    sa.Column('space_name', sa.String(length=255), nullable=False),
    sa.Column('space_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('homepage_id', sa.String(length=32), nullable=True),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('cloud_id', 'space_id')
    )
    op.create_table('confluence_sync_states',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cloud_id', sa.String(length=128), nullable=False, comment='Atlassian Cloud ID'),
    sa.Column('space_key', sa.String(length=128), nullable=False, comment='Confluence Space Key'),
    sa.Column('entity_type', sa.String(length=50), nullable=False, comment='page, blogpost'),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True, comment='마지막 동기화 시작 시간'),
    sa.Column('last_successful_sync_at', sa.DateTime(timezone=True), nullable=True, comment='마지막 성공적인 동기화 시간 (증분 동기화 기준)'),
    sa.Column('last_sync_status', sa.String(length=20), nullable=True, comment='pending, in_progress, success, failed'),
    sa.Column('last_sync_error', sa.String(length=1000), nullable=True, comment='마지막 에러 메시지'),
    sa.Column('total_entities', sa.Integer(), nullable=False, comment='동기화 대상 총 엔티티 수'),
    sa.Column('synced_entities', sa.Integer(), nullable=False, comment='동기화 완료된 엔티티 수'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_confluence_sync_states_cloud_id'), 'confluence_sync_states', ['cloud_id'], unique=False)
    op.create_table('confluence_users',
    sa.Column('cloud_id', sa.String(length=128), nullable=False),
    sa.Column('account_id', sa.String(length=128), nullable=False),
    sa.Column('account_type', sa.String(length=20), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('public_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('time_zone', sa.String(length=100), nullable=True),
    sa.Column('locale', sa.String(length=50), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('is_external_collaborator', sa.Boolean(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('cloud_id', 'account_id')
    )
    op.create_index(op.f('ix_confluence_users_email'), 'confluence_users', ['email'], unique=False)
    op.create_table('github_installation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('installation_id', sa.BigInteger(), nullable=False),
    sa.Column('account_type', sa.String(length=20), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False, comment='GitHub Account ID'),
    sa.Column('account_login', sa.String(length=255), nullable=False, comment='Organization or User login name'),
    sa.Column('account_avatar_url', sa.String(length=500), nullable=True),
    sa.Column('repository_selection', sa.String(length=20), nullable=True, comment='all: 모든 레포 접근 / selected: 선택된 레포만'),
    sa.Column('suspended_at', sa.DateTime(timezone=True), nullable=True, comment='일시 중지된 경우'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_github_installation_installation_id'), 'github_installation', ['installation_id'], unique=True)
    op.create_table('github_repositories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('installation_id', sa.BigInteger(), nullable=False, comment='GitHub App Installation ID'),
    sa.Column('repo_id', sa.BigInteger(), nullable=False, comment='GitHub Repository ID'),
    sa.Column('owner', sa.String(length=255), nullable=False, comment='Repository owner (user or org)'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Repository name'),
    sa.Column('full_name', sa.String(length=512), nullable=False, comment='Full name (owner/repo)'),
    sa.Column('description', sa.String(length=2000), nullable=True, comment='Repository description'),
    sa.Column('html_url', sa.String(length=512), nullable=False, comment='Repository URL'),
    sa.Column('default_branch', sa.String(length=255), nullable=False, comment='Default branch name'),
    sa.Column('language', sa.String(length=100), nullable=True, comment='Primary programming language'),
    sa.Column('topics', sa.String(length=1000), nullable=True, comment='Repository topics (JSON array as string)'),
    sa.Column('stargazers_count', sa.Integer(), nullable=False, comment='Star count'),
    sa.Column('forks_count', sa.Integer(), nullable=False, comment='Fork count'),
    sa.Column('open_issues_count', sa.Integer(), nullable=False, comment='Open issues count'),
    sa.Column('private', sa.Boolean(), nullable=False, comment='Private repository'),
    sa.Column('archived', sa.Boolean(), nullable=False, comment='Archived repository'),
    sa.Column('disabled', sa.Boolean(), nullable=False, comment='Disabled repository'),
    sa.Column('pushed_at', sa.DateTime(timezone=True), nullable=True, comment='마지막 push 시간'),
    sa.Column('repo_created_at', sa.DateTime(timezone=True), nullable=True, comment='Repository 생성 시간'),
    sa.Column('repo_updated_at', sa.DateTime(timezone=True), nullable=True, comment='Repository 업데이트 시간'),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_id')
    )
    op.create_index(op.f('ix_github_repositories_full_name'), 'github_repositories', ['full_name'], unique=True)
    op.create_index(op.f('ix_github_repositories_installation_id'), 'github_repositories', ['installation_id'], unique=False)
    op.create_index(op.f('ix_github_repositories_owner'), 'github_repositories', ['owner'], unique=False)
    op.create_table('github_sync_states',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('installation_id', sa.BigInteger(), nullable=False, comment='GitHub App Installation ID'),
    sa.Column('repository_full_name', sa.String(length=255), nullable=False, comment='Repository full name (owner/repo)'),
    sa.Column('entity_type', sa.String(length=50), nullable=False, comment='issue, pull_request, commit, repository'),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True, comment='마지막 동기화 시작 시간'),
    sa.Column('last_successful_sync_at', sa.DateTime(timezone=True), nullable=True, comment='마지막 성공적인 동기화 시간 (증분 동기화 기준)'),
    sa.Column('last_sync_status', sa.String(length=20), nullable=True, comment='pending, in_progress, success, failed'),
    sa.Column('last_sync_error', sa.String(length=1000), nullable=True, comment='마지막 에러 메시지'),
    sa.Column('total_entities', sa.Integer(), nullable=False, comment='동기화 대상 총 엔티티 수'),
    sa.Column('synced_entities', sa.Integer(), nullable=False, comment='동기화 완료된 엔티티 수'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_github_sync_states_installation_id'), 'github_sync_states', ['installation_id'], unique=False)
    op.create_index(op.f('ix_github_sync_states_repository_full_name'), 'github_sync_states', ['repository_full_name'], unique=False)
    op.create_table('github_users',
    sa.Column('database_id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=255), nullable=False, comment='Login ID'),
    sa.Column('name', sa.String(length=255), nullable=True, comment='Display Name'),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('org_role', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('database_id')
    )
    op.create_index(op.f('ix_github_users_email'), 'github_users', ['email'], unique=False)
    op.create_index(op.f('ix_github_users_login'), 'github_users', ['login'], unique=True)
    op.create_table('incremental_record_states',
    sa.Column('record_key', sa.String(length=255), nullable=False),
    sa.Column('connector', sa.String(length=32), nullable=False),
    sa.Column('scope_id', sa.String(length=255), nullable=False),
    sa.Column('record_type', sa.String(length=64), nullable=False),
    sa.Column('record_id', sa.String(length=255), nullable=False),
    sa.Column('parent_type', sa.String(length=64), nullable=False),
    sa.Column('parent_id', sa.String(length=255), nullable=False),
    sa.Column('event_kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'debouncing'"), nullable=False),
    sa.Column('generation', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('attempt', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_event_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('debounce_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('queued_generation', sa.Integer(), nullable=True),
    sa.Column('processing_generation', sa.Integer(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('lease_owner', sa.String(length=255), nullable=True),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('debouncing', 'queued', 'processing', 'retry_wait', 'dead', 'synced')", name='ck_incremental_record_states_status'),
    sa.CheckConstraint('attempt >= 0', name='ck_incremental_record_states_attempt_non_negative'),
    sa.CheckConstraint('generation >= 1', name='ck_incremental_record_states_generation_positive'),
    sa.CheckConstraint('processing_generation IS NULL OR processing_generation >= 1', name='ck_incremental_record_states_processing_generation_positive'),
    sa.CheckConstraint('queued_generation IS NULL OR queued_generation >= 1', name='ck_incremental_record_states_queued_generation_positive'),
    sa.PrimaryKeyConstraint('record_key')
    )
    op.create_index('idx_incremental_record_states_connector_status_debounce_until', 'incremental_record_states', ['connector', 'status', 'debounce_until'], unique=False)
    op.create_index('idx_incremental_record_states_connector_status_next_retry_at', 'incremental_record_states', ['connector', 'status', 'next_retry_at'], unique=False)
    op.create_index('idx_incremental_record_states_parent_status', 'incremental_record_states', ['connector', 'scope_id', 'parent_type', 'parent_id', 'status'], unique=False)
    op.create_index('idx_incremental_record_states_scope_updated_at', 'incremental_record_states', ['scope_id', 'updated_at'], unique=False)
    op.create_table('jira_projects',
    sa.Column('cloud_id', sa.String(length=128), nullable=False, comment='Jira Cloud ID'),
    sa.Column('project_key', sa.String(length=20), nullable=False, comment='프로젝트 키 (CATCH)'),
    sa.Column('project_id', sa.String(length=32), nullable=False, comment='Jira 내부 ID'),
    sa.Column('project_name', sa.String(length=255), nullable=False, comment='프로젝트 이름'),
    sa.Column('description', sa.String(length=4000), nullable=True, comment='프로젝트 설명'),
    sa.Column('project_type', sa.String(length=32), nullable=True, comment='software/business/service_desk'),
    sa.Column('lead_account_id', sa.String(length=128), nullable=True, comment='프로젝트 리드 account_id'),
    sa.Column('lead_display_name', sa.String(length=255), nullable=True, comment='프로젝트 리드 표시 이름'),
    sa.Column('url', sa.String(length=512), nullable=True, comment='프로젝트 URL'),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('cloud_id', 'project_key')
    )
    op.create_table('jira_sprints',
    sa.Column('cloud_id', sa.String(length=128), nullable=False, comment='Jira Cloud ID'),
    sa.Column('sprint_id', sa.Integer(), nullable=False, comment='Sprint ID'),
    sa.Column('sprint_name', sa.String(length=255), nullable=False, comment='스프린트 이름'),
    sa.Column('state', sa.String(length=20), nullable=True, comment='future/active/closed'),
    sa.Column('goal', sa.String(length=2000), nullable=True, comment='스프린트 목표'),
    sa.Column('project_key', sa.String(length=20), nullable=True, comment='연결된 프로젝트 키'),
    sa.Column('board_id', sa.Integer(), nullable=True, comment='보드 ID'),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('complete_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('cloud_id', 'sprint_id')
    )
    op.create_index(op.f('ix_jira_sprints_project_key'), 'jira_sprints', ['project_key'], unique=False)
    op.create_table('jira_sync_states',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cloud_id', sa.String(length=128), nullable=False, comment='Jira Cloud ID'),
    sa.Column('project_key', sa.String(length=50), nullable=True, comment='Jira Project Key'),
    sa.Column('entity_type', sa.String(length=50), nullable=False, comment='issue, epic, project, sprint'),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True, comment='마지막 동기화 시작 시간'),
    sa.Column('last_successful_sync_at', sa.DateTime(timezone=True), nullable=True, comment='마지막 성공적인 동기화 시간 (증분 동기화 기준)'),
    sa.Column('last_sync_status', sa.String(length=20), nullable=True, comment='pending, in_progress, success, failed'),
    sa.Column('last_sync_error', sa.String(length=1000), nullable=True, comment='마지막 에러 메시지'),
    sa.Column('total_entities', sa.Integer(), nullable=False, comment='동기화 대상 총 엔티티 수'),
    sa.Column('synced_entities', sa.Integer(), nullable=False, comment='동기화 완료된 엔티티 수'),
    sa.Column('oldest_entity_created_at', sa.DateTime(timezone=True), nullable=True, comment='동기화된 엔티티 중 가장 오래된 생성 시간 (이 시점 이후 데이터만 보유)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jira_sync_states_cloud_id'), 'jira_sync_states', ['cloud_id'], unique=False)
    op.create_index(op.f('ix_jira_sync_states_project_key'), 'jira_sync_states', ['project_key'], unique=False)
    op.create_table('jira_users',
    sa.Column('cloud_id', sa.String(length=128), nullable=False, comment='Jira Cloud ID'),
    sa.Column('account_id', sa.String(length=128), nullable=False, comment='Atlassian Account ID'),
    sa.Column('account_type', sa.String(length=20), nullable=False, comment='atlassian/app/customer'),
    sa.Column('active', sa.Boolean(), nullable=False, comment='활성 상태'),
    sa.Column('display_name', sa.String(length=100), nullable=False, comment='표시 이름'),
    sa.Column('email_address', sa.String(length=255), nullable=True, comment='이메일 (권한에 따라 수집 불가)'),
    sa.Column('avatar_url', sa.String(length=500), nullable=True, comment='프로필 이미지 URL'),
    sa.Column('self_url', sa.String(length=500), nullable=True, comment='Jira API self URL'),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('cloud_id', 'account_id')
    )
    op.create_table('jira_webhook_subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cloud_id', sa.String(length=128), nullable=False),
    sa.Column('webhook_id', sa.Integer(), nullable=False),
    sa.Column('callback_url', sa.String(length=1000), nullable=False),
    sa.Column('jql_filter', sa.String(length=2000), nullable=True),
    sa.Column('events_csv', sa.String(length=2000), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cloud_id', 'webhook_id', name='uq_jira_webhook_subscriptions_cloud_webhook')
    )
    op.create_index(op.f('ix_jira_webhook_subscriptions_cloud_id'), 'jira_webhook_subscriptions', ['cloud_id'], unique=False)
    op.create_table('pre_mapping_buffers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sub', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False, comment='OAuth 사용자 이메일 (예: Keycloak 이메일)'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='IDP에 등록된 임직원 실명'),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('external_user_identifier', sa.String(length=128), nullable=False),
    sa.Column('is_registered', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', 'source_type', name='uq_email_source_buffer')
    )
    op.create_index(op.f('ix_pre_mapping_buffers_email'), 'pre_mapping_buffers', ['email'], unique=False)
    op.create_table('slack_channel_members',
    sa.Column('team_id', sa.String(length=20), nullable=False, comment='WorkspaceID'),
    sa.Column('channel_id', sa.String(length=20), nullable=False, comment='ChannelID'),
    sa.Column('user_id', sa.String(length=20), nullable=False, comment='UserID'),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('team_id', 'channel_id', 'user_id')
    )
    op.create_table('slack_channel_sync_states',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.String(length=128), nullable=False, comment='Slack Team/Workspace ID'),
    sa.Column('channel_id', sa.String(length=128), nullable=False, comment='Slack Channel ID'),
    sa.Column('channel_name', sa.String(length=255), nullable=True, comment='채널명 (디버깅/로깅용)'),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True, comment='마지막 동기화 시작 시간'),
    sa.Column('last_successful_sync_at', sa.DateTime(timezone=True), nullable=True, comment='마지막 성공적인 동기화 시간 (재시도 기준점)'),
    sa.Column('last_sync_status', sa.String(length=20), nullable=True, comment='pending, in_progress, success, failed'),
    sa.Column('last_sync_error', sa.String(length=1000), nullable=True, comment='마지막 에러 메시지'),
    sa.Column('synced_count', sa.Integer(), nullable=False, comment='동기화 완료된 메시지 수'),
    sa.Column('oldest_ts', sa.String(length=50), nullable=True, comment='동기화 시작 Slack timestamp'),
    sa.Column('latest_synced_ts', sa.String(length=50), nullable=True, comment='마지막으로 성공한 메시지의 timestamp (재시도 시작점)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='채널별 동기화 상태 추적'
    )
    op.create_index(op.f('ix_slack_channel_sync_states_channel_id'), 'slack_channel_sync_states', ['channel_id'], unique=False)
    op.create_index(op.f('ix_slack_channel_sync_states_team_id'), 'slack_channel_sync_states', ['team_id'], unique=False)
    op.create_table('slack_channels',
    sa.Column('id', sa.String(length=20), nullable=False, comment='Channel ID (C456DEF)'),
    sa.Column('team_id', sa.String(length=20), nullable=False, comment='Workspace ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='채널 이름'),
    sa.Column('channel_type', sa.String(length=16), nullable=False, comment='public/private/dm/mpim'),
    sa.Column('topic', sa.String(length=1000), nullable=True, comment='채널 토픽'),
    sa.Column('purpose', sa.String(length=1000), nullable=True, comment='채널 목적'),
    sa.Column('creator_id', sa.String(length=20), nullable=True, comment='생성자 user_id'),
    sa.Column('member_count', sa.Integer(), nullable=False, comment='멤버 수'),
    sa.Column('is_archived', sa.Boolean(), nullable=False, comment='아카이브 여부'),
    sa.Column('is_private', sa.Boolean(), nullable=False, comment='비공개 여부'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='채널 생성 시간'),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slack_channels_team_id'), 'slack_channels', ['team_id'], unique=False)
    op.create_table('slack_oauth_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.String(length=20), nullable=False, comment='Slack Workspace ID'),
    sa.Column('team_name', sa.String(length=255), nullable=True, comment='Slack Workspace 이름'),
    sa.Column('bot_user_id', sa.String(length=20), nullable=False, comment='Bot User ID'),
    sa.Column('bot_access_token', sa.String(length=512), nullable=False, comment='Bot Access Token (xoxb-)'),
    sa.Column('bot_scopes', sa.String(length=1000), nullable=False, comment='Bot Token에 부여된 scopes'),
    sa.Column('authed_user_id', sa.String(length=20), nullable=True, comment='OAuth 인증한 사용자 ID'),
    sa.Column('bot_refresh_token', sa.String(length=512), nullable=True, comment='Bot Refresh Token (Token Rotation 사용 시)'),
    sa.Column('bot_token_expires_at', sa.DateTime(timezone=True), nullable=True, comment='Bot Token 만료 시간 (Token Rotation 사용 시)'),
    sa.Column('incoming_webhook_url', sa.String(length=500), nullable=True, comment='Incoming Webhook URL'),
    sa.Column('incoming_webhook_channel', sa.String(length=100), nullable=True, comment='Incoming Webhook 채널'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slack_oauth_tokens_team_id'), 'slack_oauth_tokens', ['team_id'], unique=True)
    op.create_table('slack_sync_states',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.String(length=128), nullable=False, comment='Slack Team/Workspace ID'),
    sa.Column('entity_type', sa.String(length=50), nullable=False, comment='message, channel, user, file, workspace'),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True, comment='마지막 동기화 시작 시간'),
    sa.Column('last_successful_sync_at', sa.DateTime(timezone=True), nullable=True, comment='마지막 성공적인 동기화 시간 (증분 동기화 기준)'),
    sa.Column('last_sync_status', sa.String(length=20), nullable=True, comment='pending, in_progress, success, failed'),
    sa.Column('last_sync_error', sa.String(length=1000), nullable=True, comment='마지막 에러 메시지'),
    sa.Column('total_entities', sa.Integer(), nullable=False, comment='동기화 대상 총 엔티티 수'),
    sa.Column('synced_entities', sa.Integer(), nullable=False, comment='동기화 완료된 엔티티 수'),
    sa.Column('oldest_ts', sa.String(length=50), nullable=True, comment='동기화 시작 Slack timestamp (oldest 파라미터)'),
    sa.Column('latest_ts', sa.String(length=50), nullable=True, comment='동기화 종료 Slack timestamp (latest 파라미터)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slack_sync_states_team_id'), 'slack_sync_states', ['team_id'], unique=False)
    op.create_table('slack_users',
    sa.Column('team_id', sa.String(length=20), nullable=False, comment='WorkSpaceId'),
    sa.Column('user_id', sa.String(length=20), nullable=False, comment='UserId'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Login Name Used for Mention'),
    sa.Column('real_name', sa.String(length=255), nullable=False, comment='실제 이름'),
    sa.Column('deleted', sa.Boolean(), nullable=False, comment='비활성 사용자 여부'),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True, comment='직함'),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('tz', sa.String(length=64), nullable=True, comment='타임존 ID'),
    sa.Column('tz_label', sa.String(length=128), nullable=True, comment='타임존 라벨'),
    sa.Column('is_bot', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_owner', sa.Boolean(), nullable=False),
    sa.Column('is_restricted', sa.Boolean(), nullable=False, comment='Guest User'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='프로필 업데이트 시간'),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('team_id', 'user_id')
    )
    op.create_index(op.f('ix_slack_users_email'), 'slack_users', ['email'], unique=False)
    op.create_table('slack_workspaces',
    sa.Column('id', sa.String(length=20), nullable=False, comment='Team ID (T123ABC)'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='워크스페이스 이름'),
    sa.Column('domain', sa.String(length=255), nullable=False, comment='{domain}.slack.com'),
    sa.Column('url', sa.String(length=512), nullable=False, comment='https://{domain}.slack.com/'),
    sa.Column('email_domain', sa.String(length=255), nullable=True, comment='허용 이메일 도메인'),
    sa.Column('icon_url', sa.String(length=512), nullable=True),
    sa.Column('enterprise_id', sa.String(length=32), nullable=True, comment='Enterprise Grid ID'),
    sa.Column('enterprise_name', sa.String(length=255), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_jobs',
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('connector', sa.String(length=32), nullable=False),
    sa.Column('sync_type', sa.String(length=16), nullable=False),
    sa.Column('scope_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('succeeded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('embedding_tokens_used', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('summary_tokens_used', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'in_progress', 'success', 'failed')", name='ck_sync_jobs_status'),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index('idx_sync_jobs_connector_status_requested_at', 'sync_jobs', ['connector', 'status', 'requested_at'], unique=False)
    op.create_index('idx_sync_jobs_scope_id_requested_at', 'sync_jobs', ['scope_id', 'requested_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('given_name', sa.String(length=50), nullable=True),
    sa.Column('family_name', sa.String(length=50), nullable=True),
    sa.Column('picture', sa.String(length=500), nullable=True),
    sa.Column('role', sa.String(length=20), server_default=sa.text("'user'"), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('refresh_token', sa.String(length=500), nullable=True),
    sa.Column('department', sa.String(length=50), server_default=sa.text("'unregistered'"), nullable=False),
    sa.Column('job_level', sa.String(length=20), server_default=sa.text("'member'"), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('custom_prompt', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('inactive_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reactivated', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'deactivated_at', name='uq_inactive_user_timestamp')
    )
    op.create_index('idx_inactive_users_user_id', 'inactive_users', ['user_id'], unique=False)
    op.create_table('incremental_stream_outbox',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('record_key', sa.String(length=255), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('connector', sa.String(length=32), nullable=False),
    sa.Column('scope_id', sa.String(length=255), nullable=False),
    sa.Column('parent_type', sa.String(length=64), nullable=False),
    sa.Column('parent_id', sa.String(length=255), nullable=False),
    sa.Column('event_kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('attempt', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('stream_message_id', sa.String(length=64), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'publishing', 'published', 'skipped', 'failed')", name='ck_incremental_stream_outbox_status'),
    sa.CheckConstraint('attempt >= 0', name='ck_incremental_stream_outbox_attempt_non_negative'),
    sa.CheckConstraint('generation >= 1', name='ck_incremental_stream_outbox_generation_positive'),
    sa.ForeignKeyConstraint(['record_key'], ['incremental_record_states.record_key'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('record_key', 'generation', name='uq_incremental_stream_outbox_record_generation')
    )
    op.create_index('idx_incremental_stream_outbox_connector_status_created_at', 'incremental_stream_outbox', ['connector', 'status', 'created_at'], unique=False)
    op.create_index('idx_incremental_stream_outbox_status_created_at', 'incremental_stream_outbox', ['status', 'created_at'], unique=False)
    op.create_table('oauth_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sub', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('picture', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_users_email'), 'oauth_users', ['email'], unique=True)
    op.create_index(op.f('ix_oauth_users_sub'), 'oauth_users', ['sub'], unique=True)
    op.create_table('sync_events',
    sa.Column('event_id', sa.String(length=32), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('connector', sa.String(length=32), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=False),
    sa.Column('resource_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('publish_status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('attempt', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default=sa.text('3'), nullable=False),
    sa.Column('publish_attempt', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('succeeded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('embedding_tokens_used', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('summary_tokens_used', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('stream_message_id', sa.String(length=64), nullable=True),
    sa.Column('publish_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("publish_status IN ('pending', 'publishing', 'published', 'failed')", name='ck_sync_events_publish_status'),
    sa.CheckConstraint("status IN ('pending', 'in_progress', 'success', 'failed', 'retrying')", name='ck_sync_events_status'),
    sa.CheckConstraint('attempt <= max_attempts', name='ck_sync_events_attempt_lte_max'),
    sa.CheckConstraint('attempt >= 0', name='ck_sync_events_attempt_non_negative'),
    sa.CheckConstraint('max_attempts >= 1', name='ck_sync_events_max_attempts_positive'),
    sa.CheckConstraint('publish_attempt >= 0', name='ck_sync_events_publish_attempt_non_negative'),
    sa.ForeignKeyConstraint(['job_id'], ['sync_jobs.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('idx_sync_events_connector_status_requested_at', 'sync_events', ['connector', 'status', 'requested_at'], unique=False)
    op.create_index('idx_sync_events_job_id_requested_at', 'sync_events', ['job_id', 'requested_at'], unique=False)
    op.create_index('idx_sync_events_job_id_status', 'sync_events', ['job_id', 'status'], unique=False)
    op.create_index('idx_sync_events_publish_status_requested_at', 'sync_events', ['publish_status', 'requested_at'], unique=False)
    op.create_table('user_source_mappings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('external_user_identifier', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'source_type', name='uq_user_source')
    )
    op.create_table('workspaces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_rooms',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_rooms_session_id'), 'chat_rooms', ['session_id'], unique=True)
    op.create_index(op.f('ix_chat_rooms_user_id'), 'chat_rooms', ['user_id'], unique=False)
    op.create_index(op.f('ix_chat_rooms_workspace_id'), 'chat_rooms', ['workspace_id'], unique=False)
    op.create_table('knowledge_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('display_name', sa.String(length=20), nullable=False),
    sa.Column('external_identifier', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_sources_external_identifier'), 'knowledge_sources', ['external_identifier'], unique=False)
    op.create_table('user_workspaces',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'workspace_id')
    )
    op.create_table('chat_histories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_room_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('sender_type', sa.String(length=20), nullable=False),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True),
    sa.Column('is_liked', sa.Boolean(), nullable=True, comment='True: 긍정, False: 부정, None: 평가 없음'),
    sa.Column('feedback_reasons', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True, comment='사용자가 선택한 부정 피드백 사유 목록 (Json Array)'),
    sa.Column('feedback_comment', sa.Text(), nullable=True, comment='사용자가 직접 작성한 상세 피드백 내용'),
    sa.Column('is_displayed', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='사용자가 수정한 쿼리인 경우에만 False이며 화면에 노출되지 않음.'),
    sa.Column('is_saved', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='사용자가 저장한 답변'),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_room_id'], ['chat_rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chat_history_content_bigm', 'chat_histories', ['content'], unique=False, postgresql_using='gin', postgresql_ops={'content': 'gin_bigm_ops'})
    op.create_index(op.f('ix_chat_histories_chat_room_id'), 'chat_histories', ['chat_room_id'], unique=False)
    op.create_index(op.f('ix_chat_histories_is_saved'), 'chat_histories', ['is_saved'], unique=False)
    op.create_index('ix_chat_histories_is_saved_true', 'chat_histories', ['is_saved'], unique=False, postgresql_where=sa.text('is_saved IS TRUE'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chat_histories_is_saved_true', table_name='chat_histories', postgresql_where=sa.text('is_saved IS TRUE'))
    op.drop_index(op.f('ix_chat_histories_is_saved'), table_name='chat_histories')
    op.drop_index(op.f('ix_chat_histories_chat_room_id'), table_name='chat_histories')
    op.drop_index('idx_chat_history_content_bigm', table_name='chat_histories', postgresql_using='gin', postgresql_ops={'content': 'gin_bigm_ops'})
    op.drop_table('chat_histories')
    op.drop_table('user_workspaces')
    op.drop_index(op.f('ix_knowledge_sources_external_identifier'), table_name='knowledge_sources')
    op.drop_table('knowledge_sources')
    op.drop_index(op.f('ix_chat_rooms_workspace_id'), table_name='chat_rooms')
    op.drop_index(op.f('ix_chat_rooms_user_id'), table_name='chat_rooms')
    op.drop_index(op.f('ix_chat_rooms_session_id'), table_name='chat_rooms')
    op.drop_table('chat_rooms')
    op.drop_table('workspaces')
    op.drop_table('user_source_mappings')
    op.drop_index('idx_sync_events_publish_status_requested_at', table_name='sync_events')
    op.drop_index('idx_sync_events_job_id_status', table_name='sync_events')
    op.drop_index('idx_sync_events_job_id_requested_at', table_name='sync_events')
    op.drop_index('idx_sync_events_connector_status_requested_at', table_name='sync_events')
    op.drop_table('sync_events')
    op.drop_index(op.f('ix_oauth_users_sub'), table_name='oauth_users')
    op.drop_index(op.f('ix_oauth_users_email'), table_name='oauth_users')
    op.drop_table('oauth_users')
    op.drop_index('idx_incremental_stream_outbox_status_created_at', table_name='incremental_stream_outbox')
    op.drop_index('idx_incremental_stream_outbox_connector_status_created_at', table_name='incremental_stream_outbox')
    op.drop_table('incremental_stream_outbox')
    op.drop_index('idx_inactive_users_user_id', table_name='inactive_users')
    op.drop_table('inactive_users')
    op.drop_table('users')
    op.drop_index('idx_sync_jobs_scope_id_requested_at', table_name='sync_jobs')
    op.drop_index('idx_sync_jobs_connector_status_requested_at', table_name='sync_jobs')
    op.drop_table('sync_jobs')
    op.drop_table('slack_workspaces')
    op.drop_index(op.f('ix_slack_users_email'), table_name='slack_users')
    op.drop_table('slack_users')
    op.drop_index(op.f('ix_slack_sync_states_team_id'), table_name='slack_sync_states')
    op.drop_table('slack_sync_states')
    op.drop_index(op.f('ix_slack_oauth_tokens_team_id'), table_name='slack_oauth_tokens')
    op.drop_table('slack_oauth_tokens')
    op.drop_index(op.f('ix_slack_channels_team_id'), table_name='slack_channels')
    op.drop_table('slack_channels')
    op.drop_index(op.f('ix_slack_channel_sync_states_team_id'), table_name='slack_channel_sync_states')
    op.drop_index(op.f('ix_slack_channel_sync_states_channel_id'), table_name='slack_channel_sync_states')
    op.drop_table('slack_channel_sync_states')
    op.drop_table('slack_channel_members')
    op.drop_index(op.f('ix_pre_mapping_buffers_email'), table_name='pre_mapping_buffers')
    op.drop_table('pre_mapping_buffers')
    op.drop_index(op.f('ix_jira_webhook_subscriptions_cloud_id'), table_name='jira_webhook_subscriptions')
    op.drop_table('jira_webhook_subscriptions')
    op.drop_table('jira_users')
    op.drop_index(op.f('ix_jira_sync_states_project_key'), table_name='jira_sync_states')
    op.drop_index(op.f('ix_jira_sync_states_cloud_id'), table_name='jira_sync_states')
    op.drop_table('jira_sync_states')
    op.drop_index(op.f('ix_jira_sprints_project_key'), table_name='jira_sprints')
    op.drop_table('jira_sprints')
    op.drop_table('jira_projects')
    op.drop_index('idx_incremental_record_states_scope_updated_at', table_name='incremental_record_states')
    op.drop_index('idx_incremental_record_states_parent_status', table_name='incremental_record_states')
    op.drop_index('idx_incremental_record_states_connector_status_next_retry_at', table_name='incremental_record_states')
    op.drop_index('idx_incremental_record_states_connector_status_debounce_until', table_name='incremental_record_states')
    op.drop_table('incremental_record_states')
    op.drop_index(op.f('ix_github_users_login'), table_name='github_users')
    op.drop_index(op.f('ix_github_users_email'), table_name='github_users')
    op.drop_table('github_users')
    op.drop_index(op.f('ix_github_sync_states_repository_full_name'), table_name='github_sync_states')
    op.drop_index(op.f('ix_github_sync_states_installation_id'), table_name='github_sync_states')
    op.drop_table('github_sync_states')
    op.drop_index(op.f('ix_github_repositories_owner'), table_name='github_repositories')
    op.drop_index(op.f('ix_github_repositories_installation_id'), table_name='github_repositories')
    op.drop_index(op.f('ix_github_repositories_full_name'), table_name='github_repositories')
    op.drop_table('github_repositories')
    op.drop_index(op.f('ix_github_installation_installation_id'), table_name='github_installation')
    op.drop_table('github_installation')
    op.drop_index(op.f('ix_confluence_users_email'), table_name='confluence_users')
    op.drop_table('confluence_users')
    op.drop_index(op.f('ix_confluence_sync_states_cloud_id'), table_name='confluence_sync_states')
    op.drop_table('confluence_sync_states')
    op.drop_table('confluence_spaces')
    op.drop_table('companies')
    op.drop_index(op.f('ix_atlassian_oauth_tokens_cloud_id'), table_name='atlassian_oauth_tokens')
    op.drop_table('atlassian_oauth_tokens')
    # ### end Alembic commands ###
