"""Add chat_token_usages and drop token columns from chat_histories

Revision ID: e4c8353eade9
Revises: 740d7e16753a
Create Date: 2026-03-20 04:48:07.142805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e4c8353eade9'
down_revision: Union[str, Sequence[str], None] = '740d7e16753a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_token_usages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=50), nullable=False),
    sa.Column('token_breakdown', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['chat_histories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chat_token_usages_company_time', 'chat_token_usages', ['company_id', 'created_at'], unique=False)
    op.create_index('idx_chat_token_usages_user_time', 'chat_token_usages', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_chat_token_usages_workspace_time', 'chat_token_usages', ['workspace_id', 'created_at'], unique=False)
    op.drop_column('chat_histories', 'output_tokens')
    op.drop_column('chat_histories', 'input_tokens')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_histories', sa.Column('input_tokens', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('chat_histories', sa.Column('output_tokens', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index('idx_chat_token_usages_workspace_time', table_name='chat_token_usages')
    op.drop_index('idx_chat_token_usages_user_time', table_name='chat_token_usages')
    op.drop_index('idx_chat_token_usages_company_time', table_name='chat_token_usages')
    op.drop_table('chat_token_usages')
    # ### end Alembic commands ###
